# To make sure uv.lock file is up to date even if pyproject.toml file
# was changed:
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.30
    hooks:
      - id: uv-lock
# To keep a requirements.txt file in sync with uv.lock file.
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.30
    hooks:
      - id: uv-export